package octopusdeploy

const (
	constDisplayName                 string = "display_name"
	constEnhancedMode                string = "enhanced_mode"
	constEnvironmentIDs              string = "environment_ids"
	constExecutablePath              string = "executable_path"
	constExtractDuringDeployment     string = "extract_during_deployment"
	constEventCategories             string = "event_categories"
	constEventGroups                 string = "event_groups"
	constFeedType                    string = "feed_type"
	constFeedURI                     string = "feed_uri"
	constInstructions                string = "instructions"
	constIsSensitive                 string = "is_sensitive"
	constKey                         string = "key"
	constPackage                     string = "package"
	constPassword                    string = "password"
	constPassphrase                  string = "passphrase"
	constPrimaryPackage              string = "primary_package"
	constProjectTrigger              string = "project_trigger"
	constPrompt                      string = "prompt"
	constProperty                    string = "property"
	constResponsibleTeams            string = "responsible_teams"
	constRoles                       string = "roles"
	constScope                       string = "scope"
	constScriptParameters            string = "script_parameters"
	constScriptFileName              string = "script_file_name"
	constSecretName                  string = "secret_name"
	constSecretValues                string = "secret_values"
	constServiceAccount              string = "service_account"
	constServiceName                 string = "service_name"
	constShouldRedeploy              string = "should_redeploy"
	constStartMode                   string = "start_mode"
	constTrue                        string = "true"
	constType                        string = "type"
	constUsername                    string = "username"
	constValue                       string = "value"
	constVariable                    string = "variable"
	constVariableSubstitutionInFiles string = "variable_substitution_in_files"
	constWindowsService              string = "windows_service"
)
