package octopusdeploy

const (
	constAccountType string = "account_type"
	// This variable is no longer being used in the resource_azure_service_principal since
	// we now have the New NewAzureServicePrincipalAccount type, so the constAccountTypeAzure
	// is no longer needed
	// constAccountTypeAzure               string = "Azure"
	constActions                    string = "actions"
	constActionType                 string = "action_type"
	constAcquisitionLocation        string = "acquisition_location"
	constAdditionalInitParams       string = "additional_init_params"
	constAddress                    string = "address"
	constAPIKey                     string = "apikey"
	constArguments                  string = "arguments"
	constAutomaticDeploymentTargets string = "automatic_deployment_targets"
	constChannels                   string = "channels"
	constClientID                   string = "client_id"
	constClientSecret               string = "client_secret"
	constCustomAccountName          string = "custom_account_name"
	constCustomAccountPassword      string = "custom_account_password"
	constDependencies               string = "dependencies"
	/* #nosec */
	constDeploymentProcess                  string = "deployment_process"
	constDisplayName                        string = "display_name"
	constEmptyString                        string = ""
	constEnhancedMode                       string = "enhanced_mode"
	constEnvironmentIDs                     string = "environment_ids"
	constEnvironments                       string = "environments"
	constExcludedEnvironments               string = "excluded_environments"
	constExecutablePath                     string = "executable_path"
	constExtractDuringDeployment            string = "extract_during_deployment"
	constEventCategories                    string = "event_categories"
	constEventGroups                        string = "event_groups"
	constFeed                               string = "feed"
	constFeedID                             string = "feed_id"
	constFeedType                           string = "feed_type"
	constFeedURI                            string = "feed_uri"
	constInstructions                       string = "instructions"
	constIsOptionalPhase                    string = "is_optional_phase"
	constIsSensitive                        string = "is_sensitive"
	constKey                                string = "key"
	constMachines                           string = "machines"
	constMinimumEnvironmentsBeforePromotion string = "minimum_environments_before_promotion"
	constOptionalDeploymentTargets          string = "optional_deployment_targets"
	constPackage                            string = "package"
	constPackageID                          string = "package_id"
	constPassword                           string = "password"
	constPassphrase                         string = "passphrase"
	constPrimaryPackage                     string = "primary_package"
	constProjectTrigger                     string = "project_trigger"
	constPrompt                             string = "prompt"
	constProperty                           string = "property"
	constQuantityToKeep                     string = "quantity_to_keep"
	constRequired                           string = "required"
	constResponsibleTeams                   string = "responsible_teams"
	constRoles                              string = "roles"
	constRunOnServer                        string = "run_on_server"
	constScope                              string = "scope"
	constScriptParameters                   string = "script_parameters"
	constScriptFileName                     string = "script_file_name"
	constSecretName                         string = "secret_name"
	constSecretValues                       string = "secret_values"
	constSensitiveValue                     string = "sensitive_value"
	constServiceAccount                     string = "service_account"
	constServiceName                        string = "service_name"
	constShouldRedeploy                     string = "should_redeploy"
	constShouldKeepForever                  string = "should_keep_forever"
	constSpaceID                            string = "space_id"
	constStartMode                          string = "start_mode"
	constSubscriptionID                     string = "subscription_id"
	constTrue                               string = "true"
	constType                               string = "type"
	constUnit                               string = "unit"
	constUsername                           string = "username"
	constValue                              string = "value"
	constVariable                           string = "variable"
	constVariableSubstitutionInFiles        string = "variable_substitution_in_files"
	constWindowsService                     string = "windows_service"
	constWorkerPoolID                       string = "worker_pool_id"

	CertificateIDs                                 string = "Certificate_ids"
	EndpointCommunicationStyle                     string = "endpoint_communicationstyle"
	EndpointProxyID                                string = "endpoint_proxyid"
	EndpointTentacleVersionDetailsUpgradeLocked    string = "endpoint_tentacleversiondetails_upgradelocked"
	EndpointTentacleVersionDetailsUpgradeRequired  string = "endpoint_tentacleversiondetails_upgraderequired"
	EndpointTentacleVersionDetailsUpgradeSuggested string = "endpoint_tentacleversiondetails_upgradesuggested"
	EndpointTentacleVersionDetailsVersion          string = "endpoint_tentacleversiondetails_version"
	Extract                                        string = "Extract"
	HasLatestCalamari                              string = "haslatestcalamari"
	IsDefault2                                     string = "isdefault"
	IsInProcess                                    string = "isinprocess"
	MachinePolicy                                  string = "machinepolicy"
	StatusSummary                                  string = "statussummary"
)
