before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - "-s -w -X main.version={{.Version}} -X main.commit={{.Commit}}"
    goos:
      - darwin
      - freebsd
      - linux
      - windows
    goarch:
      - '386'
      - amd64
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
    binary: "{{ .ProjectName }}_v{{ .Version }}"
archives:
  - format: zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
changelog:
  filters:
    exclude:
      - "^test:"
      - "^README.md"
      - "^.goreleaser.yaml"
  groups:
    - title: 'New Features and Updates'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Breaking Changes'
      regexp: "^.*break[(\\w)]*:+.*$"
      order: 1
    - title: 'Bug Fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 10
    - title: 'Documentation Updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 20
    - title: Other Work
      order: 999
  sort: asc
  use: github