name: Validate Docs
on:
  push:
    branches:
      - '**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: '1.22'
      - run: go generate main.go

      - name: Stage new and modified files in docs folder
        run: git add docs/

      - name: Check for file changes
        run: git diff --cached --exit-code
