name: Prevent New Terraform SDK additions

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  detect-new-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Compare directories
        run: |
          git fetch origin
          git diff --name-status origin/main..$GITHUB_REF | grep '^A' | grep '^A\s\+octopusdeploy/' > new_files.txt
          if [ -s new_files.txt ]; then
            echo "New files have been added to the 'directory/' directory:"
            cat new_files.txt
            exit 1
          else
            echo "No new files detected in the 'directory/' directory."
          fi
